apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ingress-nginx
  - ./sources
  - ./external-secrets-operator
  - ./cert-manager
  - ./external-dns
  - ./storageClasses
