---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord-webhook-url
  labels:
    component: alertmanager
    used_case: discord-webhook-url
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-cluster-secret-store
  target:
    name: discord-webhook-url
    template:
      engineVersion: v2
      data:
        discord-webhook-url: "{{ .discordWebhookUrl }}"
  data:
  - secretKey: discordWebhookUrl
    remoteRef:
      key: discord-webhook-url
