apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chart:
    spec:
      ## https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
      chart: kube-prometheus-stack
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux
      version: 52.1.0
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  dependsOn:
  - name: external-secrets-operator
    namespace: flux
  ## https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=values
  values:
    alertmanager:
      ingress:
        enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: 'letsencrypt-prod'
        hosts:
          - host: alertmanager.k8s.learndevops.in
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: kube-prom-stack-alertmanager
            hosts:
              - alertmanager.k8s.learndevops.in
