apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux
      version: 1.13.1
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  dependsOn:
    - name: external-secrets-operator
  interval: 5m
  # https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml
  values:
    serviceAccount:
      name: sa-external-dns
      create: true
      labels:
        azure.workload.identity/use: "true"
      annotations:
        azure.workload.identity/client-id: "7134739d-992f-42e0-b2b8-a19f07b65175"
        azure.workload.identity/tenant-id: 62143b67-6780-4dd3-8294-f784d7bac864
    podLabels:
      azure.workload.identity/use: "true"
    provider: azure
    secretConfiguration:
      enabled: true
      mountPath: "/etc/kubernetes/"
      data:
        azure.json: |
          {
            "subscriptionId": "df30c82e-30e4-4ab5-80ce-8d4aef10990d",
            "resourceGroup": "rg-kubernetes-projects",
            "useWorkloadIdentityExtension": true
          }
