apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  # annotations:
  #   helm.sh/resource-policy: keep ## ## to keep the pv after uninstalling the helm chart
  name: standard-lrs-retain
provisioner: disk.csi.azure.com
##? ref:https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/driver-parameters.md
parameters:
  skuName: StandardSSD_ZRS
  fsType: xfs
  cachingMode: ReadOnly
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
