apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets-operator
spec:
  chart:
    spec:
      chart: external-secrets
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: external-secrets-operator
        namespace: flux
      version: 0.9.7
  timeout: 10m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 5m
  # https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets?modal=values
  values:
    serviceAccount:
      name: sa-external-secrets-operator
      create: true
      annotations:
        azure.workload.identity/client-id: '1e7b7eb4-9cac-43b9-b55a-38d2f4e4b638'
        azure.workload.identity/tenant-id: 62143b67-6780-4dd3-8294-f784d7bac864
    podLabels:
      azure.workload.identity/use: 'true'
      ## kube-prometheus-stack helmrelease name
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
