---
## Workload Identity ref: https://github.com/external-secrets/external-secrets/blob/9be0f87794ca2d8986805662035fc6caeec60ba3/docs/snippets/azkv-workload-identity.yaml
## ref: https://external-secrets.io/v0.4.4/provider-azure-key-vault/
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-cluster-secret-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://k8s-projects-secrets-01.vault.azure.net/"
      serviceAccountRef:
        name: sa-external-secrets-operator
        namespace: flux
