##? ref: https://external-secrets.io/v0.4.4/provider-azure-key-vault/
##? ref: https://docs.gitops.weave.works/docs/configuration/oidc-access/
##? ref: https://external-secrets.io/v0.9.5/guides/all-keys-one-secret/
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-auth
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-cluster-secret-store
  target:
    name: oidc-auth
    template:
      engineVersion: v2
      data:
        clientID: "{{ .clientid }}"
        clientSecret: "{{ .clientsecret }}"
        issuerURL: "https://login.microsoftonline.com/{{ .tenantid }}/v2.0"
        redirectURL: https://flux-dashboard.k8s.learndevops.in/oauth2/callback
        customScopes: openid,email,offline_access,profile
  data:
    - secretKey: clientid
      remoteRef:
        key: spn-flux-dashboard-oidc-clientid
    - secretKey: clientsecret
      remoteRef:
        key: spn-flux-dashboard-oidc-clientsecret
    - secretKey: tenantid
      remoteRef:
        key: tenantid
