apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
##* Add metadata.namspace =  flux to create resources in flux namespace
##* Not over-riding the namesapce value from kustomization
resources:
  - ./release.yaml
  - ./namespace.yaml
  - ./volumeSnapshotClass.yaml
