##? ref : https://external-secrets.io/v0.9.8/guides/templating/#templatefrom
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord-webhook-url
  labels:
    component: alertmanager
    used_case: discord-webhook-url
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-cluster-secret-store
  target:
    name: discord-webhook-url
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: alertmanager-config-tpl
            items:
              - key: alertmanager.yaml
  data:
    - secretKey: discordWebhookUrl
      remoteRef:
        key: discord-webhook-url
