apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - grafana-admin-externalSecret.yaml
  - basic-auth-externalSecret.yaml
  - discord-webhook-url.yaml
  - alertmanager-config-tpl.yaml
namespace: flux ## over-rides namespace in all resources associated with it.