---
## https://cert-manager.io/docs/configuration/acme/dns01/azuredns/#configure-a-clusterissuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: ishansharma887@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          azureDNS:
            environment: AzurePublicCloud
            hostedZoneName: k8s.learndevops.in
            resourceGroupName: rg-kubernetes-projects
            subscriptionID: df30c82e-30e4-4ab5-80ce-8d4aef10990d
            managedIdentity:
              clientID: 15eeb354-decf-4282-95f7-079efe464f87
