apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml
  - https://raw.githubusercontent.com/ishuar/kubernetes-in-real-life/main/azure-kubernetes-service/expose-sample-app-with-ingress/sample-app.yaml
namespace: flux
