apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
spec:
  chart:
    spec:
      chart: nginx-gateway-fabric
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: nginxinc
        namespace: flux
      version: 1.0.0
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  timeout: 10m
  interval: 5m
  # https://github.com/nginxinc/nginx-gateway-fabric/blob/v1.0.0/deploy/helm-chart/values.yaml
  values:
    service:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: '/healthz'
