apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager # { artifact-hub-package: helm/cert-manager/cert-manager }
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux
      version: v1.13.0
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  dependsOn:
  - name: external-secrets-operator
    namespace: flux
  ## https://artifacthub.io/packages/helm/cert-manager/cert-manager/1.13.0?modal=values
  values:
    installCRDs: true
    extraArgs:
      - --enable-certificate-owner-ref=true
    prometheus:
      enabled: false
      serviceMonitor:
        enabled: false
    global:
      logLevel: 3
    podLabels:
      azure.workload.identity/use: "true"
    serviceAccount:
      name: sa-cert-manager
      annotations:
        azure.workload.identity/client-id: aeef2603-0dae-4649-9761-b38bfd176869
      labels:
        azure.workload.identity/use: "true"
