apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux
      version: 4.7.1
  interval: 5m
  timeout: 10m
  # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
  values:
    controller:
      ingressClassResource:
        controllerValue: k8s.io/ingress-nginx
        default: true
        enabled: true
        name: nginx
      metrics:
        enabled: true
        serviceMonitor:
          additionalLabels:
            release: kube-prometheus-stack
          enabled: false
      minAvailable: '50%'
      service:
        ## https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/#loadbalancer-annotations
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: '/healthz'
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 4
        targetCPUUtilizationPercentage: 90
        targetMemoryUtilizationPercentage: 90
      podSecurityContext:
        runAsNonRoot: true
        seccompProfile:
          type: 'RuntimeDefault'
        allowPrivilegeEscalation: false
