apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-blackbox-exporter
  annotations:
    metadata.weave.works/description: This is the source location for the prometheus-blackbox-exporter helm chart.
  labels:
    app.kubernetes.io/component: HelmRepository
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/used-case: endpoints-probing
spec:
  interval: 30m
  type: oci
  ##? OCI reference: https://github.com/prometheus-community/helm-charts/blob/84ab6297ac99330cf3dc3d9c68d811172582acaa/.github/workflows/release.yaml#L60C33-L60C80
  url: oci://ghcr.io/prometheus-community/charts
