apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-azure
spec:
  chart:
    spec:
      chart: ingress-azure
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: azure-application-gateway-ingress-controller
        namespace: flux
      version: 1.7.2
  interval: 1m
  timeout: 10m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: agic-values
