apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-azure
spec:
  chart:
    spec:
      chart: ingress-azure
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: azure-application-gateway-ingress-controller
        namespace: flux
      version: 1.7.2
  interval: 1m
  timeout: 10m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  # valuesFrom:
  #   - kind: ConfigMap
  #     name: agic-values
  values:
  # ref: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/helm/ingress-azure/values.yaml
    verbosityLevel: 3
    image:
      repository: mcr.microsoft.com/azure-application-gateway/kubernetes-ingress
      tag: 1.7.2
      pullPolicy: Always

      # Set this to override the default ingress class value. DEFAULT: azure/application-gateway
      # This can be used to segregate ingress controllers in the same namespace
      # ingressClass: agic-2

      # Set Ingress class resource to use the IngressClass V1 resource with Ingress V1
      ingressClassResource:
        name: azure-application-gateway
        enabled: true
        default: false
        controllerValue: 'azure/application-gateway'
    appgw:
      environment: AZUREPUBLICCLOUD
      resourceGroup: agic-poc-rg
      name: agic-poc-gateway
      # Whether to force private IP for all the listeners on Application Gateway
      usePrivateIP: false
    armAuth:
      type: workloadIdentity
      identityClientID: 9df4e4a0-cc33-4e7b-9202-fd5dce48deed ## NOT FROM PERSONAL SUBSCRIPTION ## ::commerce::

    # Specify if the cluster is RBAC enabled or not
    rbac:
      enabled: true # true/false
