## ref: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/helm/ingress-azure/values.yaml
verbosityLevel: 3
image:
  repository: mcr.microsoft.com/azure-application-gateway/kubernetes-ingress
  tag: 1.7.2
  pullPolicy: Always

kubernetes:
  ingressClassResource:
    name: azure-application-gateway
    enabled: true
    default: false
    controllerValue: 'azure/application-gateway'

appgw:
  environment: AZUREPUBLICCLOUD
  resourceGroup: agic-poc-rg
  name: agic-poc-gateway
  usePrivateIP: false

armAuth:
  type: workloadIdentity
  identityClientID: 9df4e4a0-cc33-4e7b-9202-fd5dce48deed ## NOT FROM PERSONAL SUBSCRIPTION ## ::commerce::

rbac:
  enabled: true # true/false
