# ref: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/helm/ingress-azure/values.yaml

# The values.yaml file is important to templates.
# This file contains the default values for a chart.
# These values may be overridden during helm install or helm upgrade.

# Verbosity level of the App Gateway Ingress Controller
verbosityLevel: 3

# Reconcile period is time period after which AGIC will re-configure Application Gateway if the current state differs from the expected state.
# If not specified, periodic reconcile is turned off. Range: 30 - 300 (seconds)
# reconcilePeriodSeconds: 30

image:
  repository: mcr.microsoft.com/azure-application-gateway/kubernetes-ingress
  tag: 1.6.0
  pullPolicy: Always

  # Set this to override the default ingress class value. DEFAULT: azure/application-gateway
  # This can be used to segregate ingress controllers in the same namespace
  # ingressClass: agic-2

  # Set Ingress class resource to use the IngressClass V1 resource with Ingress V1
  ingressClassResource:
    name: azure-application-gateway
    enabled: true
    default: false
    controllerValue: 'azure/application-gateway'

################################################################################
# Specify which application gateway the ingress controller will manage
# Specity which cloud environment will be used AZURECHINACLOUD,AZUREGERMANCLOUD,AZUREPUBLICCLOUD,AZUREUSGOVERNMENTCLOUD default: AZUREPUBLICCLOUD
#
appgw:
  environment: AZUREPUBLICCLOUD
  # subscriptionId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  resourceGroup: agic-poc-rg
  name: agic-poc-gateway
  # Whether to force private IP for all the listeners on Application Gateway
  usePrivateIP: false
  # subResourceNamePrefix: "myPrefix"

################################################################################
# Specify the authentication with Azure Resource Manager

# - Option 3: Workload Identity (https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview)
armAuth:
  type: workloadIdentity
  identityClientID: 9df4e4a0-cc33-4e7b-9202-fd5dce48deed ## NOT FROM PERSONAL SUBSCRIPTION ## ::commerce::

################################################################################
# (Legacy: use `kubernetes.nodeSelector` instead) Specify the scheduling options
nodeSelector: {}

################################################################################
# Specify if the cluster is RBAC enabled or not
rbac:
  enabled: false # true/false
